* What is camome?
  Camome is a Rails application to collect data from various application and organize them.

* Setup Ruby Environment
  | Ruby  | 2.1.5 |
  | Rails | 4.1.8 |

  I recommend you to install new Ruby and Bundler on the top of Rbenv before install camome.

  1) Install rbenv + ruby-build (check https://github.com/rbenv/rbenv#basic-github-checkout for details)
     #+BEGIN_SRC sh
     $ git clone git@github.com:rbenv/rbenv.git ~/.rbenv
     $ git clone git@github.com:rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
     # Edit your shell dot files to add some path and environment variables.
     #+END_SRC

  2) Install Ruby and Bundler
     #+BEGIN_SRC sh
     # Install ruby 2.1.5
     $ rbenv install 2.1.5

     # Installation check
     $ rbenv global 2.1.5
     $ ruby -v # -> You will see: ruby 2.1.5...

     # Install bundler for your new Ruby
     $ gem install bundler

     # Activate bundler
     $ rbenv rehash

     # Get back to your system default Ruby if you want
     $ rbenv global system # say, /usr/bin/ruby
     $ ruby -v
     #+END_SRC

* Install camome
** Clone camome
   1) clone camome from github
      #+BEGIN_SRC sh
      $ git clone git@github.com:nomlab/camome.git ~/Programs/camome
      #+END_SRC

   2) Setup to use installed ruby
      #+BEGIN_SRC sh
      $ cd ~/Programs/camome
      $ ruby -v # -> You will see: ruby 2.1.5...
      #+END_SRC

** Setup camome
   1) Install vendor/bundle stuffs
      #+BEGIN_SRC sh
      $ bundle install --path vendor/bundle
      #+END_SRC

   2) Setup secret key
      #+BEGIN_SRC sh
      $ bundle exec rake secret # -> You will see: foobarbuz... Copy the string.
      $ cp config/secrets-example.yml config/secrets.yml
      $ vim config/secrets.yml # -> Replace all <SECRETKEY> with the string outputted
      #+END_SRC

   3) Setup DB
      #+BEGIN_SRC sh
      $ bundle exec rake db:migrate
      #+END_SRC

   4) Initialize DB
      #+BEGIN_SRC sh
      $ bundle exec rake db:seed
      #+END_SRC

   5) Install submodule
      #+BEGIN_SRC sh
      $ git submodule init
      $ git submodule update
      #+END_SRC

* Launch camome
  1) Launch camome app
     #+BEGIN_SRC sh
     $ bundle exec rails s
     #+END_SRC

  2) Open =http://localhost:3000= in the web browser
     #+BEGIN_SRC sh
     # Example
     $ open http://localhost:3000
     #+END_SRC

* Help
** Default user
   #+BEGIN_SRC sh
   Login name:admin
   Password:  admin
   #+END_SRC

** Create new user
   1) Access to =http://localhost:3000/users=, and click "New User"
   2) After creating new user, access to =http://localhost:3000/gate/logout= to logout current user
   3) Make sure that you can login with the created user.
