##
## config/application_settings.yml
##
##
default: &default
  oauth:
    google:
      application_id: XXXXXXXXXXXXXXXXX
      application_secret: XXXXXXXXXXXXXXXXX
  redis:
    url: redis://XXXXX:6379

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
