default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: camome_development
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: camome_test